version: '3'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 6200:6200
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - api