version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/app
    ports:
      - 6200:6200
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
  client:
    build: ./client
    volumes:
      - ./client:/usr/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - api